const bcrypt = require("bcrypt");
const Router = require("express").Router();
//const UserModel = require("../schema/user")
const OrderModel = require("../schemas/orders")
const AuthMiddleware = require("../middleware/userAuth")
var express = require('express');
//var router = express.Router();


const jwt = require("jsonwebtoken")
const SECRET_KEY = "lkhfhgdgj(*&(*$khdsd78fsadhfjkh34gh4g2&*(h4g2jh342gh3j4jg2jh4g2g4"


//add AuthMiddleWare
Router.post("/", AuthMiddleware, async (req, res) => {
    try {
        const payload = req.user;
        const { body } = req
        const { cart } = body

        const newOrder = {user: ObjectID(payload.id),orderPlacedOn:new Date(), //order ID will be autogenerated in MongoDb
            isDelivered: false,orderDeliveredOn: new Date(),cart: cart}
        const checkOut = await OrderModel.insertOne(newOrder) // {}
        checkOut.save()
        const result = {"status":"success","message": "order placed successfully"}
        res.json(result)
        console.log("order...",result)
    }
    catch (error) {
        console.log(error)
        res.status(500).json({ status: "error", message: "server error occured" })
    }
});


module.exports = Router;